version: 2.1

jobs:
  build:
    docker:
      - image: tuplestream/swift-env:latest
    steps:
      - checkout
      - run: swift test -Xcc -mcx16 -Xswiftc -DENABLE_DOUBLEWIDE_ATOMICS --verbose
  validate:
    docker:
      - image: m0wfo/tailor:0.12.0
    steps:
      - checkout
      - run: tailor --format=json ~/project
  bump_version:
    docker:
      - image: tuplestream/bumpversion:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "06:db:d2:0b:82:e7:3e:15:97:66:22:c6:57:1c:61:a7"
      - checkout
      - run:
          name: run bumpversion and push
          command: bump

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - validate
      - bump_version:
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - validate
